"""empty message

Revision ID: c2de36cda8e9
Revises: 
Create Date: 2019-09-02 12:54:55.022502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2de36cda8e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_server_code', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('numofmodules', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric2_school_server_code'), 'metric2', ['school_server_code'], unique=False)
    op.create_table('metric3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_server_code', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric3_school_server_code'), 'metric3', ['school_server_code'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('lastlogin', sa.DateTime(), nullable=True),
    sa.Column('numlogins', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_metric3_school_server_code'), table_name='metric3')
    op.drop_table('metric3')
    op.drop_index(op.f('ix_metric2_school_server_code'), table_name='metric2')
    op.drop_table('metric2')
    # ### end Alembic commands ###
